### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by dant00ine** [thmhoag/swgemu-docker#3]
Hey this is a cool repo and super easy to get started.

I'm curious; if one was to use for local dev (is this even a good idea?) how would you go about recompiling to reflect code changes?

**Comment by grpatter** [comment]
To rebuild after local changes, just re-run the docker image build (instead of (re)starting the existing image(s)).
ie. `docker-compose build`  instead of `docker-compose up`

As far as using this for local dev, it's fine. It works well enough and is highly convenient, especially with the scripts and tre directories being local mounts - very easy to work with. I was using this for some lightweight local dev on windows without much headache.

For larger dev efforts, I would recommend an actual linux machine/VM. Realistically though, if you're okay with the build process, there's no reason you can't use this - just be mindful of where your database is and acknowledge you'll be doing a full rebuild every time.
